trigger:
- 'dev-*'
- 'qa-*'
- prod
- master

variables:
  dockerRegistryServiceConnection: '58a0d1a8-4ada-4c29-bf5b-07ec8e3a39fa'
  imageRepository: 'aks-deployment'
  containerRegistry: 'master1regestry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:

# ---------------- BUILD STAGE ----------------
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build Image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push image to ACR
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

# ---------------- DEPLOY STAGE ----------------
- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: AKS Deployment
    pool:
      vmImage: $(vmImageName)
    steps:

    - script: |
        sed -i "s|IMAGE_PLACEHOLDER|$(containerRegistry)/$(imageRepository):$(tag)|g" k8s/deployment.yml
      displayName: Update image tag

    - task: Kubernetes@1
      displayName: Apply manifests to AKS
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'newsc'
        azureResourceGroup: 'mastervijay'
        kubernetesCluster: 'masterscluster'
        namespace: 'default'
        command: 'apply'
        useConfigurationFile: true
        configuration: k8s

