#Deployment ante oka pod ni create cheyyadaniki plan laga untundi. Ee YAML lo replicas: 1 undi kabatti only oka pod run avutundi. 
#Pod ki app: aksdeployment ane label istaru, andulo oka container untadi, adi IMAGE_PLACEHOLDER ane image ni use chesi 8080 port meeda app run chestundi. 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksdeployment
  template:
    metadata:
      labels:
        app: aksdeployment
    spec:
      containers:
      - name: aksdeployment
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080

