apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksdeployment
  template:
    metadata:
      labels:
        app: aksdeployment
    spec:
      containers:
      - name: aksdeployment
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080
